import { useEffect, useRef, useState } from "react";
import {
  ActivityIndicator,
  Alert,
  Dimensions,
  Linking,
  Modal,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View
} from "react-native";
import { Feather, FontAwesome, Ionicons, MaterialCommunityIcons } from "@expo/vector-icons";
import { generateRoadmapChatResponseWithGroq } from "../api/gemini";
import { colors } from "../constants/theme";
import { fonts } from "../constants/fonts";

const { width, height } = Dimensions.get("window");

const DOMAIN_OPTIONS = [
  "🌐 Full Stack Web",
  "🤖 AI & Data Science",
  "📱 Mobile App Dev",
  "☁️ Cloud & DevOps",
  "🎨 UI/UX Design"
];

const BUDGET_OPTIONS = [
  "Free / Starter",
  "₹2,000 - ₹5,000",
  "₹5,000 - ₹10,000",
  "₹10,000+ Premium"
];

export default function AiRoadmapPlannerModal({ visible, onClose, user = {} }) {
  const [messages, setMessages] = useState([]);
  const [inputText, setInputText] = useState("");
  const [loading, setLoading] = useState(false);
  const [selectedDomain, setSelectedDomain] = useState("");
  const [selectedBudget, setSelectedBudget] = useState("");
  const scrollViewRef = useRef(null);

  useEffect(() => {
    if (visible) {
      const initialGreeting = [
        {
          id: "m_1",
          sender: "ai",
          text: `Hello ${user.name || "Learner"}! 👋 I am your TCM AI Career Advisor.\n\nI will help you create a personalized learning roadmap, select the best TCM courses, and estimate your budget.`,
          time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })
        },
        {
          id: "m_2",
          sender: "ai",
          text: `Which domain or field are you interested in? Tap a quick option below or type your career goals:`,
          time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })
        }
      ];
      setMessages(initialGreeting);
      setSelectedDomain("");
      setSelectedBudget("");
      setInputText("");
    }
  }, [visible]);

  useEffect(() => {
    setTimeout(() => {
      scrollViewRef.current?.scrollToEnd({ animated: true });
    }, 150);
  }, [messages, loading]);

  async function handleSend(textToSend = inputText) {
    const cleanText = (textToSend || "").trim();
    if (!cleanText || loading) return;

    const userMsg = {
      id: `u_${Date.now()}`,
      sender: "user",
      text: cleanText,
      time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })
    };

    setMessages((prev) => [...prev, userMsg]);
    setInputText("");
    setLoading(true);

    try {
      const aiReplyText = await generateRoadmapChatResponseWithGroq(
        messages,
        cleanText,
        selectedDomain,
        selectedBudget
      );

      const aiMsg = {
        id: `ai_${Date.now()}`,
        sender: "ai",
        text: aiReplyText,
        time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })
      };

      setMessages((prev) => [...prev, aiMsg]);
    } catch (error) {
      setMessages((prev) => [
        ...prev,
        {
          id: `ai_err_${Date.now()}`,
          sender: "ai",
          text: "I've structured your career roadmap! Based on your input, we recommend starting with TCM Academy Full Stack Web Dev or AI Masterclass. Tap below to send your complete roadmap to WhatsApp!",
          time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })
        }
      ]);
    } finally {
      setLoading(false);
    }
  }

  function handleSelectDomain(domain) {
    setSelectedDomain(domain);
    handleSend(`I am interested in ${domain}. Please suggest a roadmap and TCM courses.`);
  }

  function handleSelectBudget(budget) {
    setSelectedBudget(budget);
    handleSend(`My target budget range is ${budget}. Please customize my course roadmap accordingly.`);
  }

  function handleSendToWhatsApp() {
    const userName = user.name || "TCM Student";
    const lastAiMsg = [...messages].reverse().find((m) => m.sender === "ai")?.text || "Personalized Learning Roadmap";

    const waMessage =
      `🎓 *TCM ACADEMY - PERSONALIZED LEARNING ROADMAP* 🎓\n\n` +
      `👤 *Student Name:* ${userName}\n` +
      `🎯 *Target Field:* ${selectedDomain || "Software Development"}\n` +
      `💰 *Planned Budget:* ${selectedBudget || "Flexible"}\n\n` +
      `----------------------------------------\n` +
      `🗺️ *AI ROADMAP SUMMARY & RECOMMENDATION:*\n\n` +
      `${lastAiMsg.slice(0, 1200)}\n\n` +
      `----------------------------------------\n` +
      `📲 *Generated by TCM AI Advisor*\n` +
      `Target Mentor Support: +91 9238695500`;

    const encodedText = encodeURIComponent(waMessage);
    const waUrl = `https://wa.me/919238695500?text=${encodedText}`;

    Linking.openURL(waUrl).catch(() => {
      Alert.alert("WhatsApp Error", "Could not open WhatsApp automatically. Destination number: 9238695500");
    });
  }

  if (!visible) return null;

  return (
    <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose} statusBarTranslucent>
      <View style={styles.modalOverlay}>
        <View style={styles.modalCard}>
          {/* Header */}
          <View style={styles.modalHeader}>
            <View style={styles.headerTitleRow}>
              <View style={styles.aiBadgeIcon}>
                <MaterialCommunityIcons name="sparkles" size={20} color="#FFFFFF" />
              </View>
              <View style={{ flex: 1 }}>
                <View style={{ flexDirection: "row", alignItems: "center", gap: 6 }}>
                  <Text style={styles.modalTitle}>Plan My Roadmap</Text>
                  <View style={styles.groqPill}>
                    <Text style={styles.groqPillText}>AI Advisor</Text>
                  </View>
                </View>
                <Text style={styles.modalSub}>TCM Career & Budget Counselor</Text>
              </View>
            </View>
            <TouchableOpacity hitSlop={12} onPress={onClose} style={styles.closeBtn}>
              <Feather name="x" size={22} color="#1E293B" />
            </TouchableOpacity>
          </View>

          {/* Quick Domain Selector Chips */}
          <View style={styles.quickChipsContainer}>
            <Text style={styles.quickChipsLabel}>Quick Domain Select:</Text>
            <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, paddingHorizontal: 12, paddingBottom: 8 }}>
              {DOMAIN_OPTIONS.map((d) => (
                <TouchableOpacity
                  key={d}
                  onPress={() => handleSelectDomain(d)}
                  style={[styles.chip, selectedDomain === d && styles.chipActive]}
                >
                  <Text style={[styles.chipText, selectedDomain === d && styles.chipTextActive]}>{d}</Text>
                </TouchableOpacity>
              ))}
            </ScrollView>
          </View>

          {/* Quick Budget Selector Chips */}
          <View style={styles.quickChipsContainer}>
            <Text style={styles.quickChipsLabel}>Budget Range:</Text>
            <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, paddingHorizontal: 12, paddingBottom: 8 }}>
              {BUDGET_OPTIONS.map((b) => (
                <TouchableOpacity
                  key={b}
                  onPress={() => handleSelectBudget(b)}
                  style={[styles.chip, selectedBudget === b && styles.chipActive]}
                >
                  <Text style={[styles.chipText, selectedBudget === b && styles.chipTextActive]}>{b}</Text>
                </TouchableOpacity>
              ))}
            </ScrollView>
          </View>

          {/* Chat Messages */}
          <ScrollView
            ref={scrollViewRef}
            style={styles.chatScroll}
            contentContainerStyle={styles.chatContent}
            showsVerticalScrollIndicator={false}
          >
            {messages.map((msg) => (
              <View
                key={msg.id}
                style={[
                  styles.msgBubble,
                  msg.sender === "user" ? styles.userBubble : styles.aiBubble
                ]}
              >
                {msg.sender === "ai" ? (
                  <View style={styles.aiSenderHeader}>
                    <MaterialCommunityIcons name="lightning-bolt" size={14} color="#5B3CF5" style={{ marginRight: 4 }} />
                    <Text style={styles.aiSenderTitle}>TCM AI Advisor</Text>
                  </View>
                ) : null}
                <Text style={[styles.msgText, msg.sender === "user" && styles.userMsgText]}>
                  {msg.text}
                </Text>
                <Text style={[styles.msgTime, msg.sender === "user" && styles.userMsgTime]}>
                  {msg.time}
                </Text>
              </View>
            ))}

            {loading ? (
              <View style={[styles.msgBubble, styles.aiBubble, { flexDirection: "row", alignItems: "center", gap: 8 }]}>
                <ActivityIndicator size="small" color="#5B3CF5" />
                <Text style={{ fontSize: 13, color: "#64748B", fontFamily: fonts.medium }}>
                  AI is designing your course roadmap & budget...
                </Text>
              </View>
            ) : null}
          </ScrollView>

          {/* WhatsApp Export Action Footer Banner */}
          {messages.length > 2 ? (
            <View style={styles.waExportBanner}>
              <View style={{ flex: 1 }}>
                <Text numberOfLines={1} style={styles.waExportTitle}>Roadmap Ready for Export 🚀</Text>
                <Text numberOfLines={1} style={styles.waExportSub}>Send full details to mentor on +91 9238695500</Text>
              </View>
              <TouchableOpacity onPress={handleSendToWhatsApp} style={styles.waBtn}>
                <FontAwesome name="whatsapp" size={18} color="#FFFFFF" style={{ marginRight: 6 }} />
                <Text style={styles.waBtnText}>Send to 9238695500</Text>
              </TouchableOpacity>
            </View>
          ) : null}

          {/* Input Box Bar */}
          <View style={styles.inputBar}>
            <TextInput
              style={styles.textInput}
              value={inputText}
              onChangeText={setInputText}
              placeholder="Ask AI e.g. How to become a MERN stack developer in 3 months?"
              placeholderTextColor="#94A3B8"
              multiline={false}
              onSubmitEditing={() => handleSend(inputText)}
            />
            <TouchableOpacity
              onPress={() => handleSend(inputText)}
              disabled={!inputText.trim() || loading}
              style={[styles.sendBtn, (!inputText.trim() || loading) && styles.sendBtnDisabled]}
            >
              <Ionicons name="send" size={18} color="#FFFFFF" />
            </TouchableOpacity>
          </View>
        </View>
      </View>
    </Modal>
  );
}

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.7)",
    justifyContent: "flex-end"
  },
  modalCard: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    height: Math.min(height * 0.9, 780),
    flexDirection: "column",
    overflow: "hidden"
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9"
  },
  headerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1
  },
  aiBadgeIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center"
  },
  modalTitle: {
    fontSize: 17,
    fontFamily: fonts.bold,
    color: "#0F172A"
  },
  groqPill: {
    backgroundColor: colors.badgeBg,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8
  },
  groqPillText: {
    fontSize: 11,
    fontFamily: fonts.bold,
    color: colors.primary
  },
  modalSub: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: "#64748B"
  },
  closeBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F8FAFC",
    alignItems: "center",
    justifyContent: "center"
  },
  quickChipsContainer: {
    paddingTop: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#F8FAFC"
  },
  quickChipsLabel: {
    fontSize: 11,
    fontFamily: fonts.bold,
    color: "#94A3B8",
    paddingHorizontal: 16,
    marginBottom: 6,
    textTransform: "uppercase"
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: "#E2E8F0"
  },
  chipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary
  },
  chipText: {
    fontSize: 12,
    fontFamily: fonts.medium,
    color: "#334155"
  },
  chipTextActive: {
    color: "#FFFFFF",
    fontFamily: fonts.bold
  },
  chatScroll: {
    flex: 1,
    backgroundColor: "#F8FAFC"
  },
  chatContent: {
    padding: 16,
    gap: 12
  },
  msgBubble: {
    maxWidth: "84%",
    padding: 14,
    borderRadius: 18
  },
  aiBubble: {
    alignSelf: "flex-start",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderBottomLeftRadius: 4
  },
  userBubble: {
    alignSelf: "flex-end",
    backgroundColor: "#5B3CF5",
    borderBottomRightRadius: 4
  },
  aiSenderHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6
  },
  aiSenderTitle: {
    fontSize: 11.5,
    fontFamily: fonts.bold,
    color: "#5B3CF5"
  },
  msgText: {
    fontSize: 13.5,
    fontFamily: fonts.regular,
    color: "#1E293B",
    lineHeight: 20
  },
  userMsgText: {
    color: "#FFFFFF"
  },
  msgTime: {
    fontSize: 10,
    color: "#94A3B8",
    alignSelf: "flex-end",
    marginTop: 6
  },
  userMsgTime: {
    color: "#E2E8F0"
  },
  waExportBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ECFDF5",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#A7F3D0",
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 10
  },
  waExportTitle: {
    fontSize: 13,
    fontFamily: fonts.bold,
    color: "#065F46"
  },
  waExportSub: {
    fontSize: 11,
    fontFamily: fonts.medium,
    color: "#047857"
  },
  waBtn: {
    backgroundColor: "#10B981",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center"
  },
  waBtnText: {
    fontSize: 12.5,
    fontFamily: fonts.bold,
    color: "#FFFFFF"
  },
  inputBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    gap: 10
  },
  textInput: {
    flex: 1,
    backgroundColor: "#F1F5F9",
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 13.5,
    fontFamily: fonts.regular,
    color: "#0F172A"
  },
  sendBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#5B3CF5",
    alignItems: "center",
    justifyContent: "center"
  },
  sendBtnDisabled: {
    backgroundColor: "#CBD5E1"
  }
});
